"""create_legal_aid_tables

Revision ID: g6h7i8j9k0l1
Revises: e5f6g7h8i9j
Create Date: 2026-02-23 14:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'g6h7i8j9k0l1'
down_revision = 'e5f6g7h8i9j'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create legal_aid_conversations table
    op.create_table('legal_aid_conversations',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('category', sa.String(length=50), nullable=False),
        sa.Column('is_shared', sa.Boolean(), nullable=False, default=False),
        sa.Column('share_token', sa.String(length=255), nullable=True),
        sa.Column('allow_public_view', sa.Boolean(), nullable=False, default=False),
        sa.Column('user_id', sa.String(length=36), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legal_aid_conversations_id'), 'legal_aid_conversations', ['id'], unique=False)
    op.create_index(op.f('ix_legal_aid_conversations_share_token'), 'legal_aid_conversations', ['share_token'], unique=True)
    op.create_index(op.f('ix_legal_aid_conversations_user_id'), 'legal_aid_conversations', ['user_id'], unique=False)
    
    # Create legal_aid_messages table
    op.create_table('legal_aid_messages',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('message_type', sa.String(length=20), nullable=False),
        sa.Column('ai_confidence', sa.Float(), nullable=True),
        sa.Column('ai_sources', sa.Text(), nullable=True),
        sa.Column('conversation_id', sa.String(length=36), nullable=False),
        sa.Column('user_id', sa.String(length=36), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['conversation_id'], ['legal_aid_conversations.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legal_aid_messages_id'), 'legal_aid_messages', ['id'], unique=False)
    op.create_index(op.f('ix_legal_aid_messages_conversation_id'), 'legal_aid_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_legal_aid_messages_user_id'), 'legal_aid_messages', ['user_id'], unique=False)
    
    # Create legal_aid_documents table
    op.create_table('legal_aid_documents',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('filename', sa.String(length=255), nullable=False),
        sa.Column('original_filename', sa.String(length=255), nullable=False),
        sa.Column('file_path', sa.String(length=500), nullable=False),
        sa.Column('file_size', sa.Integer(), nullable=False),
        sa.Column('file_type', sa.String(length=50), nullable=False),
        sa.Column('mime_type', sa.String(length=100), nullable=False),
        sa.Column('extracted_text', sa.Text(), nullable=True),
        sa.Column('ai_analysis', sa.Text(), nullable=True),
        sa.Column('conversation_id', sa.String(length=36), nullable=False),
        sa.Column('user_id', sa.String(length=36), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['conversation_id'], ['legal_aid_conversations.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legal_aid_documents_id'), 'legal_aid_documents', ['id'], unique=False)
    op.create_index(op.f('ix_legal_aid_documents_conversation_id'), 'legal_aid_documents', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_legal_aid_documents_user_id'), 'legal_aid_documents', ['user_id'], unique=False)
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_legal_aid_documents_user_id'), table_name='legal_aid_documents')
    op.drop_index(op.f('ix_legal_aid_documents_conversation_id'), table_name='legal_aid_documents')
    op.drop_index(op.f('ix_legal_aid_documents_id'), table_name='legal_aid_documents')
    op.drop_table('legal_aid_documents')
    op.drop_index(op.f('ix_legal_aid_messages_user_id'), table_name='legal_aid_messages')
    op.drop_index(op.f('ix_legal_aid_messages_conversation_id'), table_name='legal_aid_messages')
    op.drop_index(op.f('ix_legal_aid_messages_id'), table_name='legal_aid_messages')
    op.drop_table('legal_aid_messages')
    op.drop_index(op.f('ix_legal_aid_conversations_user_id'), table_name='legal_aid_conversations')
    op.drop_index(op.f('ix_legal_aid_conversations_share_token'), table_name='legal_aid_conversations')
    op.drop_index(op.f('ix_legal_aid_conversations_id'), table_name='legal_aid_conversations')
    op.drop_table('legal_aid_conversations')
    # ### end Alembic commands ###
